server:
  port: 8080

spring:
  application:
    name: must-be-the-sql-be
  datasource:
    url: jdbc:mysql://106.13.236.175:13306/sql_logic_engine?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    openai:
      api-key: sk-LRksJOdzcvC28aZjB6F3D95e37F946E49c96D23aA6D0BfCa
      base-url: https://api.v3.cm

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
